### ISSUE TITLE
Implement Workflow for Generating Sample App APKs and Enabling Direct Testing from GitHub

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-auth#77]
As part of our release and QA processes and discussed with the team, it's essential to provide a streamlined way for testers and stakeholders to access and test the latest versions of our app without the need to build it locally using Android Studio. This issue aims to implement a GitHub workflow that automates the generation of APKs for easy download and testing directly from GitHub.

**Requirements:**
1. **GitHub Workflow**: Develop a GitHub Actions workflow that automates the generation of Sample app APKs for both release and debug variants.
2. **Release and QA Testing**: Ensure that stakeholders, testers, and QA team members can easily access and download the generated APKs from GitHub releases to conduct testing.
3. **Minimal Handholding**: Design the workflow to require minimal manual intervention, allowing it to run smoothly without extensive supervision.
4. **Manual Workflow Run Support**: Enable manual triggering of the workflow to accommodate special cases or specific testing requirements.
5. **Security**: Utilize GitHub secrets for sensitive configurations or keys to ensure the security of the workflow.
6. **Documentation**: Document the workflow setup, including how to trigger manual runs, configure secrets, and access generated APKs.

**Implementation Advice:**
- **Gradle Tasks**: Utilize Gradle tasks to automate the APK generation process within the GitHub Actions workflow.
- **Conditional Workflow Triggers**: Set up conditional triggers in the workflow to run only when changes are made to relevant branches (e.g., main).
- **Parameterized Workflow**: Consider parameterizing the workflow to allow customization of build types or flavors if necessary.
- **Artifact Uploading**: Upload the generated APKs as artifacts to GitHub releases, ensuring they are easily accessible to testers.
- **Environment Setup**: Ensure the necessary build environment, such as JDK and Android SDK, is properly set up within the workflow.
- **Error Handling**: Implement robust error handling and notification mechanisms to alert team members in case of workflow failures.
- **Testing**: Test the workflow thoroughly to verify its functionality and reliability before production deployment.

**Acceptance Criteria:**
- GitHub Actions workflow is implemented to automatically generate APKs for release and debug variants.
- Stakeholders and QA team members can easily access and download APKs from GitHub releases for testing purposes.
- The workflow supports manual triggering and key configuration using GitHub secrets.
- Documentation is provided detailing the workflow setup, manual run triggering, secrets configuration, and APK access instructions.

**Applicable to Android Native and React Native sample apps**

**Comment by dzuluaga** [comment]
@Nataliagros - friendly ping.

**Comment by dzuluaga** [comment]
Friendly ping. We also need this for RN sample apps. Thanks

**Comment by dzuluaga** [comment]
Credentials shouldn't be a blocker. Same comment as [85 for maps](https://github.com/openmobilehub/android-omh-maps/issues/85)

**Comment by dzuluaga** [comment]
This task shouldn't take much time as the build is already generating the APKs. Please use the [`actions/create-release@v1`](https://github.com/actions/create-release) to release the APK. Here's an example:

```yaml
name: Build and Release APK

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug.apk
          path: app-debug.apk

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0  # Adjust the tag name as needed
          release_name: Release v1.0.0  # Adjust the release name as needed
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
```
